### ISSUE TITLE
Decide on BBB OS

### ISSUE THREAD

**Issue by brycedcarter** [eCTF/device#2]
What OS do we want to use?
Does anyone have experience with RTOSs?
My gut feeling is that we are going to want to use a basic Debian Image

thoughs?

@mkucia 
@ssussman 
@ajbezreh 
@cbabroski

**Comment by mkucia** [comment]
Big fan of Debian and it would probably be easier than RTOS to quickly integrate ideas. Unless someone is really into RTOS, then I'd vote Debian.
